version: '3.8'
services:
    web:
        build:
            context: .
            args:
                VITE_TMDB_KEY: ${VITE_TMDB_KEY}
        image: filmpire:v1.0
        environment:
            NODE_ENV: production
        ports:
            - '5173:5173'
